version: 2
updates:
- package-ecosystem: elm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: supermacro/elm-antd
    versions:
    - 7.1.1
    - 7.2.0
